"""
AssetSentinel — Evidence Layer Tests
Member 3 (Tisha) | src/backend/member3_readiness/tests/test_evidence.py

Tests all 16 required evidence scenarios:
    1.  Valid single-component evidence assembly
    2.  failure_probability → failure_risk mapping
    3.  risk_category → risk_level mapping
    4.  anomaly sensor mapping
    5.  anomaly severity mapping
    6.  maintenance status → inspection_status mapping
    7.  hours_since_service mapping
    8.  criticality mapping
    9.  generic mission impact defaults to "NONE"
    10. Multiple component evidence from a single prediction list
    11. Asset identifier mismatch rejection
    12. Component identifier mismatch rejection
    13. Invalid failure_probability rejection
    14. Invalid enum value rejection
    15. Missing required metadata rejection
    16. No readiness fields generated by the Evidence Layer

Running:
    cd src/backend/member3_readiness
    pytest tests/test_evidence.py -v
"""

from __future__ import annotations

import sys
import os
from dataclasses import replace as dataclass_replace
from datetime import datetime, timezone

import pytest

# ---------------------------------------------------------------------------
# sys.path setup — member2_ml and member3_readiness must both be importable
# ---------------------------------------------------------------------------
_BACKEND_PATH = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "..")
)
_MEMBER2_PATH = os.path.join(_BACKEND_PATH, "member2_ml")
_MEMBER3_PATH = os.path.join(_BACKEND_PATH, "member3_readiness", "..")
# member3_readiness itself needs to be importable as a package
_MEMBER3_PARENT = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..")
)

for p in [_MEMBER2_PATH, _MEMBER3_PARENT]:
    if p not in sys.path:
        sys.path.insert(0, p)

from services.prediction_service import ComponentPredictionResult  # noqa: E402
from member3_readiness.evidence.builder import (  # noqa: E402
    EvidenceAssemblyError,
    build_evidence,
    build_evidence_for_asset,
)
from member3_readiness.evidence.models import (  # noqa: E402
    ComponentInfo,
    EvidenceObject,
    MaintenanceInfo,
)


# ===========================================================================
# Test 1: Valid single-component evidence assembly
# ===========================================================================

class TestValidSingleComponentEvidence:
    def test_returns_evidence_object(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 1: Valid inputs produce a correctly typed EvidenceObject."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert isinstance(evidence, EvidenceObject)

    def test_asset_id_preserved(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert evidence.asset_id == "AS-1047"


# ===========================================================================
# Test 2: failure_probability → failure_risk
# ===========================================================================

class TestFailureProbabilityMapping:
    def test_failure_risk_equals_failure_probability(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 2: failure_probability is preserved as failure_risk (same numeric value)."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert evidence.failure_risk == as1047_prediction.failure_probability
        assert evidence.failure_risk == 0.87

    def test_failure_risk_is_not_rul(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 2b: Evidence object has no RUL field."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert not hasattr(evidence, "days_until_failure")
        assert not hasattr(evidence, "hours_until_failure")
        assert not hasattr(evidence, "remaining_useful_life")

    def test_low_failure_probability_preserved(
        self, healthy_prediction, healthy_component_info, healthy_maintenance_current
    ):
        """Test 2c: Low failure_probability maps to low failure_risk correctly."""
        evidence = build_evidence(
            healthy_prediction, healthy_component_info, healthy_maintenance_current
        )
        assert evidence.failure_risk == 0.08


# ===========================================================================
# Test 3: risk_category → risk_level
# ===========================================================================

class TestRiskCategoryMapping:
    def test_high_risk_category_maps_to_high_risk_level(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 3: risk_category HIGH maps to risk_level HIGH."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert evidence.risk_level == "HIGH"

    def test_low_risk_category_maps_to_low_risk_level(
        self, healthy_prediction, healthy_component_info, healthy_maintenance_current
    ):
        evidence = build_evidence(
            healthy_prediction, healthy_component_info, healthy_maintenance_current
        )
        assert evidence.risk_level == "LOW"

    def test_medium_risk_category_maps_to_medium_risk_level(
        self, medium_prediction, medium_component_info, medium_maintenance_scheduled
    ):
        evidence = build_evidence(
            medium_prediction, medium_component_info, medium_maintenance_scheduled
        )
        assert evidence.risk_level == "MEDIUM"


# ===========================================================================
# Test 4: anomaly sensor mapping
# ===========================================================================

class TestAnomalySensorMapping:
    def test_vibration_sensor_mapped(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 4: sensor='vibration' maps to anomaly.sensor='vibration'."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert evidence.anomaly.sensor == "vibration"

    def test_none_sensor_preserved(
        self, healthy_prediction, healthy_component_info, healthy_maintenance_current
    ):
        """Test 4b: sensor='NONE' (no anomaly) is preserved in anomaly.sensor."""
        evidence = build_evidence(
            healthy_prediction, healthy_component_info, healthy_maintenance_current
        )
        assert evidence.anomaly.sensor == "NONE"

    def test_temperature_sensor_mapped(
        self, medium_prediction, medium_component_info, medium_maintenance_scheduled
    ):
        evidence = build_evidence(
            medium_prediction, medium_component_info, medium_maintenance_scheduled
        )
        assert evidence.anomaly.sensor == "temperature"


# ===========================================================================
# Test 5: anomaly severity mapping
# ===========================================================================

class TestAnomalySeverityMapping:
    def test_high_severity_mapped(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 5: anomaly_severity HIGH maps to anomaly.severity HIGH."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert evidence.anomaly.severity == "HIGH"

    def test_low_severity_mapped(
        self, healthy_prediction, healthy_component_info, healthy_maintenance_current
    ):
        evidence = build_evidence(
            healthy_prediction, healthy_component_info, healthy_maintenance_current
        )
        assert evidence.anomaly.severity == "LOW"

    def test_anomaly_status_not_in_evidence_object(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 5b: anomaly_status (NORMAL/HIGH) is NOT forwarded to EvidenceObject."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert not hasattr(evidence.anomaly, "anomaly_status")
        assert not hasattr(evidence, "anomaly_status")


# ===========================================================================
# Test 6: maintenance status → inspection_status
# ===========================================================================

class TestMaintenanceStatusMapping:
    def test_overdue_status_mapped(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 6: maintenance status OVERDUE maps to maintenance.inspection_status OVERDUE."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert evidence.maintenance.inspection_status == "OVERDUE"

    def test_completed_status_mapped(
        self, healthy_prediction, healthy_component_info, healthy_maintenance_current
    ):
        evidence = build_evidence(
            healthy_prediction, healthy_component_info, healthy_maintenance_current
        )
        assert evidence.maintenance.inspection_status == "COMPLETED"

    def test_scheduled_status_mapped(
        self, medium_prediction, medium_component_info, medium_maintenance_scheduled
    ):
        evidence = build_evidence(
            medium_prediction, medium_component_info, medium_maintenance_scheduled
        )
        assert evidence.maintenance.inspection_status == "SCHEDULED"


# ===========================================================================
# Test 7: hours_since_service mapping
# ===========================================================================

class TestHoursSinceServiceMapping:
    def test_hours_since_service_preserved(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 7: hours_since_service 420.0 is preserved in maintenance evidence."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert evidence.maintenance.hours_since_service == 420.0

    def test_hours_since_service_healthy(
        self, healthy_prediction, healthy_component_info, healthy_maintenance_current
    ):
        evidence = build_evidence(
            healthy_prediction, healthy_component_info, healthy_maintenance_current
        )
        assert evidence.maintenance.hours_since_service == 120.0


# ===========================================================================
# Test 8: criticality mapping
# ===========================================================================

class TestCriticalityMapping:
    def test_high_criticality_mapped(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 8: component criticality HIGH is preserved in EvidenceObject."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert evidence.criticality == "HIGH"

    def test_medium_criticality_mapped(
        self, medium_prediction, medium_component_info, medium_maintenance_scheduled
    ):
        evidence = build_evidence(
            medium_prediction, medium_component_info, medium_maintenance_scheduled
        )
        assert evidence.criticality == "MEDIUM"

    def test_component_type_used_as_component_not_component_id(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 8b: EvidenceObject.component = component_type ('main_bearing'), NOT 'BRG-1047'."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert evidence.component == "main_bearing"
        assert evidence.component != "BRG-1047"


# ===========================================================================
# Test 9: generic mission impact defaults to "NONE"
# ===========================================================================

class TestMissionImpactDefault:
    def test_default_mission_impact_is_none(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 9: When no mission_impact is provided, EvidenceObject.mission_impact == 'NONE'."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert evidence.mission_impact == "NONE"

    def test_explicit_mission_impact_preserved(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 9b: Explicit mission_impact value is forwarded correctly."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue,
            mission_impact="HIGH",
        )
        assert evidence.mission_impact == "HIGH"

    def test_all_mission_impact_values_accepted(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        for level in ("NONE", "LOW", "MEDIUM", "HIGH"):
            evidence = build_evidence(
                as1047_prediction, as1047_component_info, as1047_maintenance_overdue,
                mission_impact=level,
            )
            assert evidence.mission_impact == level


# ===========================================================================
# Test 10: Multiple component evidence from a single prediction list
# ===========================================================================

class TestMultiComponentEvidence:
    def test_returns_list_of_evidence_objects(
        self,
        as1047_prediction,
        as1047_component_info,
        as1047_maintenance_overdue,
        as1047_engine_prediction,
        as1047_engine_component_info,
        as1047_engine_maintenance,
    ):
        """Test 10: build_evidence_for_asset returns one EvidenceObject per matched component."""
        predictions = [as1047_prediction, as1047_engine_prediction]
        components = [as1047_component_info, as1047_engine_component_info]
        maintenance = [as1047_maintenance_overdue, as1047_engine_maintenance]

        results = build_evidence_for_asset(predictions, components, maintenance)

        assert len(results) == 2
        assert all(isinstance(e, EvidenceObject) for e in results)

    def test_components_matched_correctly(
        self,
        as1047_prediction,
        as1047_component_info,
        as1047_maintenance_overdue,
        as1047_engine_prediction,
        as1047_engine_component_info,
        as1047_engine_maintenance,
    ):
        """Test 10b: Each EvidenceObject reflects its own component's data."""
        predictions = [as1047_prediction, as1047_engine_prediction]
        components = [as1047_component_info, as1047_engine_component_info]
        maintenance = [as1047_maintenance_overdue, as1047_engine_maintenance]

        results = build_evidence_for_asset(predictions, components, maintenance)

        bearing_evidence = next(e for e in results if e.component == "main_bearing")
        engine_evidence = next(e for e in results if e.component == "engine")

        assert bearing_evidence.failure_risk == 0.87
        assert bearing_evidence.maintenance.inspection_status == "OVERDUE"
        assert engine_evidence.failure_risk == 0.22
        assert engine_evidence.maintenance.inspection_status == "SCHEDULED"

    def test_does_not_rerun_inference(
        self,
        as1047_prediction,
        as1047_component_info,
        as1047_maintenance_overdue,
    ):
        """
        Test 10c: build_evidence_for_asset accepts a pre-fetched list and does
        not call predict_all_components() internally.
        The caller controls the prediction list — inference runs once outside.
        """
        # We pass a list with one prediction — the function must use it as-is
        results = build_evidence_for_asset(
            predictions=[as1047_prediction],
            component_info_list=[as1047_component_info],
            maintenance_info_list=[as1047_maintenance_overdue],
        )
        assert len(results) == 1
        assert results[0].failure_risk == 0.87

    def test_empty_predictions_raises_value_error(
        self, as1047_component_info, as1047_maintenance_overdue
    ):
        with pytest.raises(ValueError, match="predictions list must not be empty"):
            build_evidence_for_asset(
                predictions=[],
                component_info_list=[as1047_component_info],
                maintenance_info_list=[as1047_maintenance_overdue],
            )

    def test_empty_component_list_raises_value_error(
        self, as1047_prediction, as1047_maintenance_overdue
    ):
        with pytest.raises(ValueError, match="component_info_list must not be empty"):
            build_evidence_for_asset(
                predictions=[as1047_prediction],
                component_info_list=[],
                maintenance_info_list=[as1047_maintenance_overdue],
            )


# ===========================================================================
# Test 11: Asset identifier mismatch rejection
# ===========================================================================

class TestAssetIdentifierMismatch:
    def test_prediction_asset_mismatch_raises(
        self, as1047_prediction, as1047_maintenance_overdue
    ):
        """Test 11: prediction.asset_id != component.asset_id → EvidenceAssemblyError."""
        wrong_component = ComponentInfo(
            component_id="BRG-1047",
            asset_id="AS-9999",          # different asset
            component_type="main_bearing",
            criticality="HIGH",
        )
        with pytest.raises(EvidenceAssemblyError, match="asset_id mismatch"):
            build_evidence(as1047_prediction, wrong_component, as1047_maintenance_overdue)

    def test_maintenance_asset_mismatch_raises(
        self, as1047_prediction, as1047_component_info
    ):
        """Test 11b: prediction.asset_id != maintenance.asset_id → EvidenceAssemblyError."""
        wrong_maintenance = MaintenanceInfo(
            maintenance_id="MNT-X",
            asset_id="AS-9999",          # different asset
            component_id="BRG-1047",
            maintenance_type="INSPECTION",
            maintenance_date=datetime(2026, 9, 27, tzinfo=timezone.utc),
            status="OVERDUE",
            hours_since_service=420.0,
        )
        with pytest.raises(EvidenceAssemblyError, match="asset_id mismatch"):
            build_evidence(as1047_prediction, as1047_component_info, wrong_maintenance)


# ===========================================================================
# Test 12: Component identifier mismatch rejection
# ===========================================================================

class TestComponentIdentifierMismatch:
    def test_prediction_component_mismatch_raises(
        self, as1047_prediction, as1047_maintenance_overdue
    ):
        """Test 12: prediction.component_id != component_info.component_id → Error."""
        wrong_component = ComponentInfo(
            component_id="ENG-1047",     # different component
            asset_id="AS-1047",
            component_type="engine",
            criticality="HIGH",
        )
        with pytest.raises(EvidenceAssemblyError, match="component_id mismatch"):
            build_evidence(as1047_prediction, wrong_component, as1047_maintenance_overdue)

    def test_maintenance_component_mismatch_raises(
        self, as1047_prediction, as1047_component_info
    ):
        """Test 12b: prediction.component_id != maintenance.component_id → Error."""
        wrong_maintenance = MaintenanceInfo(
            maintenance_id="MNT-X",
            asset_id="AS-1047",
            component_id="ENG-1047",     # different component
            maintenance_type="INSPECTION",
            maintenance_date=datetime(2026, 9, 27, tzinfo=timezone.utc),
            status="OVERDUE",
            hours_since_service=420.0,
        )
        with pytest.raises(EvidenceAssemblyError, match="component_id mismatch"):
            build_evidence(as1047_prediction, as1047_component_info, wrong_maintenance)


# ===========================================================================
# Test 13: Invalid failure_probability rejection
# ===========================================================================

class TestInvalidFailureProbabilityRejection:
    def _make_prediction_with_prob(self, prob) -> ComponentPredictionResult:
        return ComponentPredictionResult(
            prediction_id="PRED-BAD",
            asset_id="AS-1047",
            component_id="BRG-1047",
            failure_probability=prob,
            risk_category="HIGH",
            anomaly_score=-0.5,
            anomaly_status="HIGH",
            anomaly_severity="HIGH",
            sensor="vibration",
            timestamp="2026-09-27T12:00:00+00:00",
        )

    def test_probability_above_1_rejected(
        self, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 13: failure_probability > 1.0 → EvidenceAssemblyError."""
        bad_pred = self._make_prediction_with_prob(1.01)
        with pytest.raises(EvidenceAssemblyError, match="failure_probability"):
            build_evidence(bad_pred, as1047_component_info, as1047_maintenance_overdue)

    def test_negative_probability_rejected(
        self, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 13b: failure_probability < 0.0 → EvidenceAssemblyError."""
        bad_pred = self._make_prediction_with_prob(-0.01)
        with pytest.raises(EvidenceAssemblyError, match="failure_probability"):
            build_evidence(bad_pred, as1047_component_info, as1047_maintenance_overdue)

    def test_boundary_values_accepted(
        self, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 13c: Exact boundary values 0.0 and 1.0 are valid."""
        for prob in (0.0, 1.0):
            pred = self._make_prediction_with_prob(prob)
            evidence = build_evidence(pred, as1047_component_info, as1047_maintenance_overdue)
            assert evidence.failure_risk == prob


# ===========================================================================
# Test 14: Invalid enum value rejection
# ===========================================================================

class TestInvalidEnumRejection:
    def test_invalid_criticality_rejected(
        self, as1047_prediction, as1047_maintenance_overdue
    ):
        """Test 14: Invalid criticality value → Pydantic ValidationError."""
        from pydantic import ValidationError
        with pytest.raises(ValidationError):
            ComponentInfo(
                component_id="BRG-1047",
                asset_id="AS-1047",
                component_type="main_bearing",
                criticality="CRITICAL",    # invalid — not in LOW/MEDIUM/HIGH
            )

    def test_invalid_maintenance_status_rejected(self):
        """Test 14b: Invalid maintenance status → Pydantic ValidationError."""
        from pydantic import ValidationError
        with pytest.raises(ValidationError):
            MaintenanceInfo(
                maintenance_id="MNT-X",
                asset_id="AS-1047",
                component_id="BRG-1047",
                maintenance_type="INSPECTION",
                maintenance_date=datetime(2026, 9, 27, tzinfo=timezone.utc),
                status="PENDING",          # invalid — not in COMPLETED/OVERDUE/SCHEDULED
                hours_since_service=420.0,
            )

    def test_invalid_mission_impact_rejected(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 14c: Invalid mission_impact → Pydantic ValidationError."""
        from pydantic import ValidationError
        with pytest.raises(ValidationError):
            build_evidence(
                as1047_prediction,
                as1047_component_info,
                as1047_maintenance_overdue,
                mission_impact="EXTREME",  # invalid — not in NONE/LOW/MEDIUM/HIGH
            )


# ===========================================================================
# Test 15: Missing required metadata rejection
# ===========================================================================

class TestMissingRequiredMetadata:
    def test_multi_component_missing_maintenance_raises(
        self,
        as1047_prediction,
        as1047_component_info,
        as1047_engine_prediction,
        as1047_engine_component_info,
    ):
        """
        Test 15: build_evidence_for_asset raises EvidenceAssemblyError when a component
        has a matching prediction but no maintenance record.
        """
        # Only provide maintenance for BRG-1047, not ENG-1047
        maintenance_only_bearing = MaintenanceInfo(
            maintenance_id="MNT-0002",
            asset_id="AS-1047",
            component_id="BRG-1047",
            maintenance_type="INSPECTION",
            maintenance_date=datetime(2026, 9, 27, tzinfo=timezone.utc),
            status="OVERDUE",
            hours_since_service=420.0,
        )
        with pytest.raises(EvidenceAssemblyError, match="No maintenance record found"):
            build_evidence_for_asset(
                predictions=[as1047_prediction, as1047_engine_prediction],
                component_info_list=[as1047_component_info, as1047_engine_component_info],
                maintenance_info_list=[maintenance_only_bearing],
            )

    def test_missing_hours_since_service_rejected(self):
        """Test 15b: hours_since_service is required in MaintenanceInfo."""
        from pydantic import ValidationError
        with pytest.raises(ValidationError):
            MaintenanceInfo(
                maintenance_id="MNT-X",
                asset_id="AS-1047",
                component_id="BRG-1047",
                maintenance_type="INSPECTION",
                maintenance_date=datetime(2026, 9, 27, tzinfo=timezone.utc),
                status="OVERDUE",
                # hours_since_service omitted intentionally
            )


# ===========================================================================
# Test 16: No readiness fields generated by Evidence Layer
# ===========================================================================

class TestNoReadinessFieldsGenerated:
    def test_evidence_object_has_no_readiness_score(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 16: EvidenceObject must NOT contain readiness_score."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert not hasattr(evidence, "readiness_score")

    def test_evidence_object_has_no_readiness_status(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 16b: EvidenceObject must NOT contain readiness_status."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert not hasattr(evidence, "readiness_status")

    def test_evidence_object_has_no_reasons(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 16c: EvidenceObject must NOT contain reasons list."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert not hasattr(evidence, "reasons")

    def test_evidence_object_has_no_recommendation_fields(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 16d: EvidenceObject must NOT contain recommendation_id or priority."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert not hasattr(evidence, "recommendation_id")
        assert not hasattr(evidence, "priority")

    def test_evidence_contains_exactly_contract_fields(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 16e: EvidenceObject contains exactly the contract §9/10 fields."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        expected_fields = {
            "asset_id", "component", "failure_risk", "risk_level",
            "anomaly", "maintenance", "criticality", "mission_impact",
        }
        actual_fields = set(EvidenceObject.model_fields.keys())
        assert actual_fields == expected_fields, (
            f"EvidenceObject fields deviate from contract §9/10.\n"
            f"Expected: {sorted(expected_fields)}\n"
            f"Got:      {sorted(actual_fields)}"
        )

    def test_component_id_not_in_evidence_object(
        self, as1047_prediction, as1047_component_info, as1047_maintenance_overdue
    ):
        """Test 16f: component_id must NOT appear in EvidenceObject (contract §10)."""
        evidence = build_evidence(
            as1047_prediction, as1047_component_info, as1047_maintenance_overdue
        )
        assert not hasattr(evidence, "component_id"), (
            "component_id must NOT be added to EvidenceObject. "
            "Contract §10 uses 'component' (display name only)."
        )
